import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.112.4";

const encoder = new TextEncoder();
type TelegramUser = { id:number; first_name:string; username?:string };
type Body = { initData?:unknown; action?:unknown; payload?:unknown };
type Db = ReturnType<typeof createClient>;
function hexToBytes(hex:string){const bytes=new Uint8Array(hex.length/2);for(let i=0;i<bytes.length;i++)bytes[i]=Number.parseInt(hex.slice(i*2,i*2+2),16);return bytes;}
async function verifyInitData(initData:string,secretHex:string){const p=new URLSearchParams(initData),hash=p.get("hash"),authRaw=p.get("auth_date"),userRaw=p.get("user");if(!hash||!/^[a-f0-9]{64}$/i.test(hash)||!authRaw||!userRaw)return{ok:false as const};const auth=Number(authRaw),now=Math.floor(Date.now()/1000);if(!Number.isInteger(auth)||auth>now+30||now-auth>3600)return{ok:false as const};const check=[...p.entries()].filter(([k])=>k!=="hash").sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${k}=${v}`).join("\n");try{const key=await crypto.subtle.importKey("raw",hexToBytes(secretHex),{name:"HMAC",hash:"SHA-256"},false,["verify"]);if(!await crypto.subtle.verify("HMAC",key,hexToBytes(hash),encoder.encode(check)))return{ok:false as const};const user=JSON.parse(userRaw) as TelegramUser;if(!Number.isSafeInteger(user.id))return{ok:false as const};return{ok:true as const,user};}catch{return{ok:false as const};}}
function payloadOf(body:Body){return typeof body.payload==="object"&&body.payload!==null?body.payload as Record<string,unknown>:{};}
function str(v:unknown){return typeof v==="string"?v:"";} function num(v:unknown){const n=Number(v);return Number.isFinite(n)?n:NaN;}
async function profile(db:Db,telegramId:number){const r=await db.from("profiles").select("id,telegram_id,first_name,username,photo_url,balance,rating,deals_count,total_profit,created_at").eq("telegram_id",telegramId).maybeSingle();if(r.error)throw new Error("profile_load_failed");return r.data;}
async function idsToItems(db:Db,ids:string[]){if(!ids.length)return[];const r=await db.from("inventory_items").select("id,owner_id,item_type_id,condition,acquired_price,acquired_at,is_locked,serial_code,specs,condition_notes,owner_count,lifetime_turnover,last_sale_price,first_seen_at,item_types(id,slug,name,brand,category_id,base_value,image_url)").in("id",ids);if(r.error)throw new Error("items_load_failed");return r.data??[];}

Deno.serve(async(req:Request)=>{
 if(req.method!=="POST")return Response.json({ok:false,error:"method_not_allowed"},{status:405});
 const secret=req.headers.get("x-tradeup-telegram-secret")??"";if(!/^[a-f0-9]{64}$/i.test(secret))return Response.json({ok:false,error:"unauthorized_server"},{status:401});
 let body:Body;try{body=await req.json();}catch{return Response.json({ok:false,error:"invalid_json"},{status:400});}
 if(typeof body.initData!=="string"||!body.initData||typeof body.action!=="string")return Response.json({ok:false,error:"invalid_payload"},{status:400});
 const verified=await verifyInitData(body.initData,secret);if(!verified.ok)return Response.json({ok:false,error:"telegram_auth_failed"},{status:401});
 const url=Deno.env.get("SUPABASE_URL"),service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!url||!service)return Response.json({ok:false,error:"server_not_configured"},{status:500});
 const db=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false}});const me=await profile(db,verified.user.id);if(!me)return Response.json({ok:false,error:"profile_not_found"},{status:404});const profileId=me.id as string,p=payloadOf(body);
 try{
  if(body.action==="overview"){
   await Promise.all([db.rpc("settle_due_auctions",{p_limit:25}),db.rpc("expire_stale_offers"),db.from("wanted_requests").update({status:"expired"}).eq("status","active").lte("expires_at",new Date().toISOString())]);
   const today=new Date();today.setUTCHours(0,0,0,0);const [stats,highlight,season,progress,claims,events,chains]=await Promise.all([
    db.from("item_market_stats").select("item_type_id,name,brand,category_id,sales_7d,sales_30d,median_7d,median_30d,median_prev_7d,low_30d,high_30d,avg_sell_seconds,active_listings,circulating").order("sales_30d",{ascending:false}).limit(18),
    db.from("market_highlights").select("highlight_date,trade_id,profile_id,item_id,profit,profit_pct,updated_at").order("highlight_date",{ascending:false}).limit(1).maybeSingle(),
    db.from("seasons").select("id,slug,name,starts_at,ends_at").eq("is_active",true).lte("starts_at",new Date().toISOString()).gt("ends_at",new Date().toISOString()).order("starts_at",{ascending:false}).limit(1).maybeSingle(),
    db.from("profile_progress").select("xp,level").eq("profile_id",profileId).maybeSingle(),
    db.from("goal_claims").select("goal_key,xp_awarded,claimed_at").eq("profile_id",profileId).eq("goal_date",new Date().toISOString().slice(0,10)),
    db.from("goal_events").select("event_type,value,meta,created_at").eq("profile_id",profileId).gte("created_at",today.toISOString()),
    db.from("flip_chains").select("id,start_capital,current_capital,trade_count,total_profit,is_active,started_at,updated_at").eq("profile_id",profileId).order("total_profit",{ascending:false}).limit(5)
   ]);if(stats.error||highlight.error||season.error||progress.error||claims.error||events.error||chains.error)throw new Error("overview_load_failed");
   let seasonStats=null,leaders:any[]=[];if(season.data){const ss=await db.from("profile_season_stats").select("season_id,profile_id,volume,profit,purchases,sales,best_margin_pct,unique_item_types").eq("season_id",season.data.id).eq("profile_id",profileId).maybeSingle();const top=await db.from("profile_season_stats").select("profile_id,profit,volume,sales,best_margin_pct").eq("season_id",season.data.id).order("profit",{ascending:false}).limit(20);if(ss.error||top.error)throw new Error("season_load_failed");seasonStats=ss.data;leaders=top.data??[];}
   let highlightItem=null,highlightProfile=null;if(highlight.data){const [it,pr]=await Promise.all([idsToItems(db,[highlight.data.item_id]),db.from("profiles").select("id,first_name,username,photo_url").eq("id",highlight.data.profile_id).maybeSingle()]);highlightItem=it[0]??null;highlightProfile=pr.data??null;}
   const ev=events.data??[];const done={first_sale:ev.some((x:any)=>x.event_type==="sale"),margin_8:ev.some((x:any)=>x.event_type==="sale"&&Number(x.meta?.margin_pct??0)>=8),fast_sale:ev.some((x:any)=>x.event_type==="fast_sale"),negotiate:ev.some((x:any)=>x.event_type==="negotiated_trade")};
   return Response.json({ok:true,profile:me,marketStats:stats.data??[],highlight:highlight.data?{...highlight.data,item:highlightItem,profile:highlightProfile}:null,season:season.data,seasonStats,seasonLeaders:leaders,progress:progress.data??{xp:0,level:1},goalClaims:claims.data??[],goalDone:done,chains:chains.data??[]});
  }
  if(body.action==="wanted"){
   await db.from("wanted_requests").update({status:"expired"}).eq("status","active").lte("expires_at",new Date().toISOString());
   const [own,publicRows,types,inventory]=await Promise.all([
    db.from("wanted_requests").select("id,buyer_id,item_type_id,budget_max,min_condition,min_storage_gb,min_battery_health,note,status,created_at,expires_at,item_types(id,slug,name,brand,category_id,base_value,image_url)").eq("buyer_id",profileId).order("created_at",{ascending:false}).limit(50),
    db.from("wanted_requests").select("id,buyer_id,item_type_id,budget_max,min_condition,min_storage_gb,min_battery_health,note,status,created_at,expires_at,item_types(id,slug,name,brand,category_id,base_value,image_url),profiles!wanted_requests_buyer_id_fkey(id,first_name,username,photo_url,rating,deals_count)").eq("status","active").neq("buyer_id",profileId).gt("expires_at",new Date().toISOString()).order("created_at",{ascending:false}).limit(100),
    db.from("item_types").select("id,slug,name,brand,category_id,base_value,image_url").eq("is_active",true).order("name"),
    db.from("inventory_items").select("id,item_type_id,condition,specs,is_locked,acquired_price,item_types(id,name,brand,category_id,image_url)").eq("owner_id",profileId).eq("is_locked",false)
   ]);if(own.error||publicRows.error||types.error||inventory.error)throw new Error("wanted_load_failed");return Response.json({ok:true,own:own.data??[],requests:publicRows.data??[],itemTypes:types.data??[],inventory:inventory.data??[]});
  }
  if(body.action==="create_wanted"){const r=await db.rpc("create_wanted_request_atomic",{p_buyer_id:profileId,p_item_type_id:str(p.itemTypeId),p_budget_max:num(p.budgetMax),p_min_condition:num(p.minCondition)||60,p_min_storage_gb:Number.isFinite(num(p.minStorageGb))?num(p.minStorageGb):null,p_min_battery_health:Number.isFinite(num(p.minBatteryHealth))?num(p.minBatteryHealth):null,p_note:str(p.note)});if(r.error)return Response.json({ok:false,error:r.error.message.split("\n")[0]},{status:409});return Response.json({ok:true,requestId:r.data});}
  if(body.action==="cancel_wanted"){const r=await db.rpc("cancel_wanted_request_atomic",{p_buyer_id:profileId,p_request_id:str(p.requestId)});if(r.error)throw new Error("wanted_cancel_failed");return Response.json({ok:true,cancelled:Boolean(r.data)});}
  if(body.action==="auctions"){
   await db.rpc("settle_due_auctions",{p_limit:50});const a=await db.from("auctions").select("id,listing_id,seller_id,start_price,current_bid,high_bidder_id,bid_count,status,ends_at,created_at,updated_at").in("status",["active","sold"]).order("created_at",{ascending:false}).limit(80);if(a.error)throw new Error("auctions_load_failed");const listingIds=(a.data??[]).map((x:any)=>x.listing_id),profileIds=[...new Set((a.data??[]).flatMap((x:any)=>[x.seller_id,x.high_bidder_id]).filter(Boolean))];const l=listingIds.length?await db.from("listings").select("id,inventory_item_id,title,price,status").in("id",listingIds):{data:[],error:null};if(l.error)throw new Error("auctions_listing_load_failed");const items=await idsToItems(db,(l.data??[]).map((x:any)=>x.inventory_item_id));const pr=profileIds.length?await db.from("profiles").select("id,first_name,username,photo_url,rating,deals_count").in("id",profileIds):{data:[],error:null};if(pr.error)throw new Error("auctions_profile_load_failed");return Response.json({ok:true,auctions:a.data??[],listings:l.data??[],items,profiles:pr.data??[]});
  }
  if(body.action==="create_auction"){const r=await db.rpc("create_auction_atomic",{p_seller_id:profileId,p_item_id:str(p.itemId),p_title:str(p.title),p_start_price:num(p.startPrice),p_duration_minutes:Number.isFinite(num(p.durationMinutes))?num(p.durationMinutes):1440});if(r.error)return Response.json({ok:false,error:r.error.message.split("\n")[0]},{status:409});return Response.json({ok:true,auctionId:r.data});}
  if(body.action==="bid_auction"){const r=await db.rpc("place_auction_bid_atomic",{p_bidder_id:profileId,p_auction_id:str(p.auctionId),p_amount:num(p.amount)});if(r.error)return Response.json({ok:false,error:r.error.message.split("\n")[0]},{status:409});return Response.json({ok:true,amount:r.data});}
  if(body.action==="bundles"){
   const b=await db.from("bundles").select("id,seller_id,title,description,price,status,created_at,updated_at").in("status",["active","sold"]).order("created_at",{ascending:false}).limit(60);if(b.error)throw new Error("bundles_load_failed");const ids=(b.data??[]).map((x:any)=>x.id);const bi=ids.length?await db.from("bundle_items").select("bundle_id,item_id").in("bundle_id",ids):{data:[],error:null};if(bi.error)throw new Error("bundle_items_load_failed");const items=await idsToItems(db,(bi.data??[]).map((x:any)=>x.item_id));const sellerIds=[...new Set((b.data??[]).map((x:any)=>x.seller_id))];const pr=sellerIds.length?await db.from("profiles").select("id,first_name,username,photo_url,rating,deals_count").in("id",sellerIds):{data:[],error:null};if(pr.error)throw new Error("bundle_profiles_load_failed");return Response.json({ok:true,bundles:b.data??[],bundleItems:bi.data??[],items,profiles:pr.data??[]});
  }
  if(body.action==="create_bundle"){const ids=Array.isArray(p.itemIds)?p.itemIds.filter((x):x is string=>typeof x==="string"):[];const r=await db.rpc("create_bundle_atomic",{p_seller_id:profileId,p_item_ids:ids,p_title:str(p.title),p_description:str(p.description),p_price:num(p.price)});if(r.error)return Response.json({ok:false,error:r.error.message.split("\n")[0]},{status:409});return Response.json({ok:true,bundleId:r.data});}
  if(body.action==="buy_bundle"){const r=await db.rpc("buy_bundle_atomic",{p_buyer_id:profileId,p_bundle_id:str(p.bundleId)});if(r.error)return Response.json({ok:false,error:r.error.message.split("\n")[0]},{status:409});return Response.json({ok:true,saleId:r.data});}
  if(body.action==="cancel_bundle"){const r=await db.rpc("cancel_bundle_atomic",{p_seller_id:profileId,p_bundle_id:str(p.bundleId)});if(r.error)throw new Error("bundle_cancel_failed");return Response.json({ok:true,cancelled:Boolean(r.data)});}
  if(body.action==="collections"){
   const [sets,entries,current,eventItems]=await Promise.all([db.from("collection_sets").select("id,name,description,sort_order").order("sort_order"),db.from("collection_entries").select("set_id,item_type_id,item_types(id,slug,name,brand,category_id,image_url)"),db.from("inventory_items").select("item_type_id").eq("owner_id",profileId),db.from("item_events").select("item_id").or(`actor_id.eq.${profileId},counterparty_id.eq.${profileId}`).limit(5000)]);if(sets.error||entries.error||current.error||eventItems.error)throw new Error("collections_load_failed");const historicalItems=await idsToItems(db,[...new Set((eventItems.data??[]).map((x:any)=>x.item_id))]);const currentIds=[...new Set((current.data??[]).map((x:any)=>x.item_type_id))],everIds=[...new Set([...currentIds,...historicalItems.map((x:any)=>x.item_type_id)])];return Response.json({ok:true,sets:sets.data??[],entries:entries.data??[],currentTypeIds:currentIds,everTypeIds:everIds});
  }
  if(body.action==="claim_goal"){const r=await db.rpc("claim_daily_goal_atomic",{p_profile_id:profileId,p_goal_key:str(p.goalKey)});if(r.error)return Response.json({ok:false,error:r.error.message.split("\n")[0]},{status:409});return Response.json({ok:true,xp:r.data});}
  if(body.action==="listing_context"){
   const listingId=str(p.listingId);const l=await db.from("listings").select("id,seller_id,inventory_item_id,title,price,status,views,created_at").eq("id",listingId).maybeSingle();if(l.error||!l.data)return Response.json({ok:false,error:"listing_not_found"},{status:404});const item=(await idsToItems(db,[l.data.inventory_item_id]))[0];if(!item)throw new Error("item_load_failed");const [events,market,reputation,favs]=await Promise.all([db.from("item_events").select("id,event_type,actor_id,counterparty_id,amount,meta,created_at").eq("item_id",item.id).order("created_at",{ascending:false}).limit(60),db.from("item_market_stats").select("*").eq("item_type_id",item.item_type_id).maybeSingle(),db.from("profile_reputation_public").select("*").eq("profile_id",l.data.seller_id).maybeSingle(),db.from("favorites").select("listing_id",{count:"exact",head:true}).eq("listing_id",listingId)]);if(events.error||market.error||reputation.error||favs.error)throw new Error("listing_context_failed");const people=[...new Set((events.data??[]).flatMap((e:any)=>[e.actor_id,e.counterparty_id]).filter(Boolean))];const pr=people.length?await db.from("profiles").select("id,first_name,username,photo_url").in("id",people):{data:[],error:null};return Response.json({ok:true,item,events:events.data??[],eventProfiles:pr.data??[],market:market.data??null,reputation:reputation.data??null,favorites:favs.count??0});
  }
  if(body.action==="rate_trade"){const r=await db.rpc("rate_trade_atomic",{p_profile_id:profileId,p_trade_id:str(p.tradeId),p_positive:p.positive===true});if(r.error)return Response.json({ok:false,error:r.error.message.split("\n")[0]},{status:409});return Response.json({ok:true});}
  if(body.action==="counter_offer"){const r=await db.rpc("counter_offer_atomic",{p_actor_id:profileId,p_offer_id:str(p.offerId),p_amount:num(p.amount),p_expires_minutes:Number.isFinite(num(p.expiresMinutes))?num(p.expiresMinutes):120,p_is_final:p.isFinal===true});if(r.error)return Response.json({ok:false,error:r.error.message.split("\n")[0]},{status:409});return Response.json({ok:true,offerId:r.data});}
  if(body.action==="respond_offer"){const r=await db.rpc("respond_negotiation_offer_atomic",{p_actor_id:profileId,p_offer_id:str(p.offerId),p_accept:p.accept===true});if(r.error)return Response.json({ok:false,error:r.error.message.split("\n")[0]},{status:409});return Response.json({ok:true,tradeId:r.data});}
  return Response.json({ok:false,error:"unknown_action"},{status:400});
 }catch(e){return Response.json({ok:false,error:e instanceof Error?e.message:"depth_failed"},{status:500});}
});