"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import Icon from "@/components/icon";

type Stats = { users:number; online:number; activeListings:number; trades:number; volume:number; fees:number; sellerProfit:number; waitingSupport:number; activeSupport:number };
type Profile = { id:string; telegram_id:number|string; first_name:string; username:string|null; photo_url:string|null; balance:number|string; rating:number; deals_count:number; total_profit:number|string; created_at:string; last_seen_at:string };
type TicketProfile = { id:string; telegram_id:number|string; first_name:string; username:string|null; photo_url:string|null };
type Ticket = { id:string; user_id:string; topic_id:string|null; status:string; last_message_at:string|null; last_message_preview:string; last_sender_type:string|null; requested_at:string|null; joined_at:string|null; closed_at?:string|null; created_at:string; updated_at:string; profiles?:TicketProfile|TicketProfile[]|null };
type Announcement = { id:string; body:string; is_active:boolean; published_at:string; created_at:string };
type Topic = { id:string; title:string; auto_reply:string; sort_order:number; is_active:boolean };
type SupportMessage = { id:string; sender_type:string; body:string; created_at:string };
type Overview = { ok:boolean; stats:Stats; users:Profile[]; tickets:Ticket[]; announcements:Announcement[]; topics:Topic[] };
type TicketDetail = { ok:boolean; ticket:Ticket; messages:SupportMessage[]; topics:Topic[] };
type Tab = "overview"|"support"|"tradeup"|"users";
type SupportFilter = "open"|"waiting"|"active"|"closed"|"all";

const money = new Intl.NumberFormat("ru-RU",{maximumFractionDigits:0});
function rub(value:number|string){return `${money.format(Number(value)||0)} ₽`;}
function date(value:string|null|undefined){return value?new Date(value).toLocaleString("ru-RU",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"}):"—";}
function time(value:string){return new Date(value).toLocaleTimeString("ru-RU",{hour:"2-digit",minute:"2-digit"});}
function profileOf(ticket:Ticket){return Array.isArray(ticket.profiles)?ticket.profiles[0]??null:ticket.profiles??null;}
function statusLabel(status:string){return status==="waiting"?"Ожидает":status==="active"?"В работе":status==="closed"?"Закрыто":"Автоответ";}
function senderLabel(type:string){return type==="user"?"Пользователь":type==="admin"?"Поддержка":type==="bot"?"Автоответ":"Система";}

function TopicEditor({topic,onSaved}:{topic:Topic;onSaved:()=>Promise<void>}){
  const [title,setTitle]=useState(topic.title),[reply,setReply]=useState(topic.auto_reply),[active,setActive]=useState(topic.is_active),[saving,setSaving]=useState(false);
  async function save(){setSaving(true);try{const r=await fetch("/api/admin",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"update_topic",id:topic.id,title,autoReply:reply,isActive:active})});if(!r.ok)throw new Error();await onSaved();}finally{setSaving(false);}}
  return <div className="proTopicEditor"><div><input value={title} onChange={(e)=>setTitle(e.target.value)}/><label><input type="checkbox" checked={active} onChange={(e)=>setActive(e.target.checked)}/>Доступен</label></div><textarea value={reply} onChange={(e)=>setReply(e.target.value)} rows={3}/><button type="button" onClick={()=>void save()} disabled={saving}>{saving?"Сохраняем…":"Сохранить"}</button></div>;
}

export default function AdminDashboardV2(){
  const [checking,setChecking]=useState(true),[configured,setConfigured]=useState(true),[authed,setAuthed]=useState(false),[key,setKey]=useState("");
  const [tab,setTab]=useState<Tab>("overview"),[overview,setOverview]=useState<Overview|null>(null),[selectedTicket,setSelectedTicket]=useState<string|null>(null),[detail,setDetail]=useState<TicketDetail|null>(null);
  const [announcement,setAnnouncement]=useState(""),[supportText,setSupportText]=useState(""),[quickReply,setQuickReply]=useState(""),[supportFilter,setSupportFilter]=useState<SupportFilter>("open"),[userQuery,setUserQuery]=useState("");
  const [busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null);const detailInFlight=useRef(false);

  async function checkAuth(){const r=await fetch("/api/admin/auth",{cache:"no-store"});const d=await r.json() as {configured?:boolean;authenticated?:boolean};setConfigured(d.configured!==false);setAuthed(d.authenticated===true);setChecking(false);return d.authenticated===true;}
  async function loadOverview(){const r=await fetch("/api/admin",{cache:"no-store"});if(r.status===401){setAuthed(false);return;}const d=await r.json() as Overview&{error?:string};if(!r.ok||!d.ok)throw new Error(d.error??"load_failed");setOverview(d);setError(null);}
  async function loadTicket(id:string){if(detailInFlight.current)return;detailInFlight.current=true;try{const r=await fetch(`/api/admin?ticketId=${encodeURIComponent(id)}`,{cache:"no-store"});const d=await r.json() as TicketDetail&{error?:string};if(!r.ok||!d.ok)throw new Error(d.error??"ticket_load_failed");setDetail(d);}finally{detailInFlight.current=false;}}

  useEffect(()=>{void checkAuth().then((ok)=>{if(ok)void loadOverview();});},[]);
  useEffect(()=>{if(!authed)return;const fromUrl=new URLSearchParams(window.location.search).get("ticket");if(fromUrl){setTab("support");setSupportFilter("all");setSelectedTicket(fromUrl);void loadTicket(fromUrl);}const timer=window.setInterval(()=>{if(document.visibilityState!=="visible")return;void loadOverview();if(selectedTicket)void loadTicket(selectedTicket);},6000);return()=>window.clearInterval(timer);},[authed,selectedTicket]);

  async function login(e:React.FormEvent){e.preventDefault();setBusy(true);setError(null);try{const r=await fetch("/api/admin/auth",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({key})});const d=await r.json() as {ok?:boolean};if(!r.ok||!d.ok)throw new Error();setAuthed(true);setKey("");await loadOverview();}catch{setError("Неверный ключ доступа");}finally{setBusy(false);}}
  async function logout(){await fetch("/api/admin/auth",{method:"DELETE"});setAuthed(false);setOverview(null);setDetail(null);}
  async function action(payload:Record<string,unknown>){setBusy(true);setError(null);try{const r=await fetch("/api/admin",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const d=await r.json() as {ok?:boolean;error?:string};if(!r.ok||!d.ok)throw new Error(d.error??"action_failed");await loadOverview();if(selectedTicket)await loadTicket(selectedTicket);return true;}catch(reason){setError(reason instanceof Error?reason.message:"action_failed");return false;}finally{setBusy(false);}}
  async function publish(e:React.FormEvent){e.preventDefault();const body=announcement.trim();if(!body)return;if(await action({action:"publish_announcement",body}))setAnnouncement("");}
  async function sendSupport(e:React.FormEvent){e.preventDefault();const body=supportText.trim();if(!body||!selectedTicket)return;setSupportText("");if(!(await action({action:"send_support",ticketId:selectedTicket,body})))setSupportText(body);}

  const tickets=overview?.tickets??[];
  const queue=useMemo(()=>[...tickets].sort((a,b)=>{const rank=(s:string)=>s==="waiting"?0:s==="active"?1:s==="bot"?2:3;return rank(a.status)-rank(b.status)||new Date(b.updated_at).getTime()-new Date(a.updated_at).getTime();}),[tickets]);
  const supportCounts=useMemo(()=>({all:queue.length,waiting:queue.filter(t=>t.status==="waiting").length,active:queue.filter(t=>t.status==="active").length,closed:queue.filter(t=>t.status==="closed").length,open:queue.filter(t=>t.status!=="closed").length}),[queue]);
  const visibleTickets=useMemo(()=>queue.filter((ticket)=>supportFilter==="all"?true:supportFilter==="open"?ticket.status!=="closed":ticket.status===supportFilter),[queue,supportFilter]);
  const visibleUsers=useMemo(()=>{const q=userQuery.trim().toLocaleLowerCase("ru");return !q?(overview?.users??[]):(overview?.users??[]).filter((u)=>`${u.first_name} ${u.username??""} ${u.telegram_id}`.toLocaleLowerCase("ru").includes(q));},[overview?.users,userQuery]);
  const selectedProfile=detail?profileOf(detail.ticket):null;
  const selectedTopic=detail?.topics.find((topic)=>topic.id===detail.ticket.topic_id)??null;

  if(checking)return <main className="proAdminLogin"><div><span className="proAdminLogo">TU</span><strong>TradeUP Control</strong><small>Проверяем сессию…</small></div></main>;
  if(!configured)return <main className="proAdminLogin"><div><span className="proAdminLogo">TU</span><strong>Панель не настроена</strong><small>Добавь ADMIN_PANEL_KEY в Vercel.</small></div></main>;
  if(!authed)return <main className="proAdminLogin"><form onSubmit={login}><span className="proAdminLogo">TU</span><div><h1>TradeUP Control</h1><p>Закрытая панель управления</p></div><label>Ключ доступа<input type="password" value={key} onChange={(e)=>setKey(e.target.value)} placeholder="••••••••••••" autoFocus/></label><button disabled={busy||!key}>{busy?"Проверяем…":"Войти"}</button>{error&&<span className="proAdminLoginError">{error}</span>}</form></main>;

  const title=tab==="overview"?"Обзор":tab==="support"?"Поддержка":tab==="tradeup"?"Официальный чат":"Пользователи";
  return <main className="proAdminShell">
    <aside className="proAdminSidebar"><div className="proAdminBrand"><span className="proAdminLogo">TU</span><div><strong>TradeUP</strong><small>Control Center</small></div></div><nav>{([['overview','Обзор','trend'],['support','Поддержка','message'],['tradeup','TradeUP чат','bot'],['users','Пользователи','user']] as const).map(([id,label,icon])=><button type="button" key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}><Icon name={icon}/><span>{label}</span>{id==="support"&&supportCounts.waiting>0&&<i>{supportCounts.waiting}</i>}</button>)}</nav><div className="proAdminSidebarFoot"><span><i/>production</span><button type="button" onClick={()=>void logout()}>Выйти</button></div></aside>

    <section className="proAdminMain"><header className="proAdminTop"><div><span>TradeUP / {title}</span><h1>{title}</h1></div><button type="button" onClick={()=>void loadOverview()}><Icon name="history" size={16}/>Обновить</button></header>{error&&<div className="proAdminAlert">{error}</div>}

      {tab==="overview"&&overview&&<div className="proOverview"><section className="proMetricGrid">{[
        ["Пользователи",overview.stats.users,"Всего аккаунтов"],["Онлайн",overview.stats.online,"За последние 5 минут"],["Активные лоты",overview.stats.activeListings,"Сейчас на рынке"],["Сделки",overview.stats.trades,"За всё время"],
        ["Оборот",rub(overview.stats.volume),"Объём сделок"],["Комиссии",rub(overview.stats.fees),"Собрано системой"],["Ждут ответа",overview.stats.waitingSupport,"Очередь поддержки"],["В работе",overview.stats.activeSupport,"Активные обращения"],
      ].map(([label,value,note])=><div key={label}><span>{label}</span><strong>{value}</strong><small>{note}</small></div>)}</section><section className="proOverviewSection"><div className="proSectionHead"><div><h2>Обращения</h2><p>Последняя активность поддержки</p></div><button type="button" onClick={()=>setTab("support")}>Открыть очередь</button></div><div className="proOverviewTickets">{queue.slice(0,8).map((ticket)=>{const p=profileOf(ticket);return <button type="button" key={ticket.id} onClick={()=>{setTab("support");setSupportFilter("all");setSelectedTicket(ticket.id);void loadTicket(ticket.id);}}><span className="proTinyAvatar">{p?.photo_url?<img src={p.photo_url} alt=""/>:p?.first_name?.charAt(0)??"T"}</span><span><strong>{p?.first_name??"Пользователь"}</strong><small>{ticket.last_message_preview||"Без сообщений"}</small></span><em className={`proStatus status-${ticket.status}`}>{statusLabel(ticket.status)}</em><time>{date(ticket.updated_at)}</time></button>;})}{queue.length===0&&<div className="proEmpty">Обращений пока нет</div>}</div></section></div>}

      {tab==="support"&&<div className="proSupportPage"><div className="proSupportFilters">{([['open','Открытые'],['waiting','Ожидают'],['active','В работе'],['closed','Закрытые'],['all','Все']] as const).map(([id,label])=><button type="button" key={id} className={supportFilter===id?"active":""} onClick={()=>setSupportFilter(id)}>{label}<span>{supportCounts[id]}</span></button>)}</div><div className="proSupportWorkspace">
        <aside className="proTicketColumn"><div className="proTicketColumnHead"><strong>Очередь</strong><span>{visibleTickets.length}</span></div><div className="proTicketScroll">{visibleTickets.map((ticket)=>{const p=profileOf(ticket);return <button type="button" key={ticket.id} className={selectedTicket===ticket.id?"proTicket active":"proTicket"} onClick={()=>{setSelectedTicket(ticket.id);void loadTicket(ticket.id);}}><span className="proTinyAvatar">{p?.photo_url?<img src={p.photo_url} alt=""/>:p?.first_name?.charAt(0)??"T"}</span><span className="proTicketCopy"><span><strong>{p?.first_name??"Пользователь"}</strong><time>{date(ticket.updated_at)}</time></span><small>{ticket.last_message_preview||"Выбран автоответ"}</small><em className={`proStatus status-${ticket.status}`}>{statusLabel(ticket.status)}</em></span></button>;})}{visibleTickets.length===0&&<div className="proEmpty">В этой очереди пусто</div>}</div></aside>

        <section className="proSupportChat">{detail&&selectedTicket?<><header><div className="proSupportPerson"><span className="proTinyAvatar large">{selectedProfile?.photo_url?<img src={selectedProfile.photo_url} alt=""/>:selectedProfile?.first_name?.charAt(0)??"T"}</span><div><strong>{selectedProfile?.first_name??"Пользователь"}</strong><small>{selectedProfile?.username?`@${selectedProfile.username}`:`Telegram ${selectedProfile?.telegram_id??""}`}</small></div></div><em className={`proStatus status-${detail.ticket.status}`}>{statusLabel(detail.ticket.status)}</em></header><div className="proSupportMessages">{detail.messages.length===0&&<div className="proEmpty">Сообщений пока нет</div>}{detail.messages.map((message)=><div key={message.id} className={`proSupportMessage ${message.sender_type}`}><span>{senderLabel(message.sender_type)}</span><p>{message.body}</p><time>{time(message.created_at)}</time></div>)}</div><div className="proSupportComposer">{detail.ticket.status!=="closed"&&<><div className="proQuickReplyLine"><select value={quickReply} onChange={(e)=>{const id=e.target.value;setQuickReply(id);const topic=detail.topics.find(t=>t.id===id);if(topic)setSupportText(topic.auto_reply);}}><option value="">Быстрый ответ…</option>{detail.topics.filter(t=>t.is_active).map((topic)=><option key={topic.id} value={topic.id}>{topic.title}</option>)}</select>{detail.ticket.status!=="active"&&<button type="button" onClick={()=>void action({action:"join_support",ticketId:selectedTicket})}>Взять в работу</button>}</div><form onSubmit={sendSupport}><textarea value={supportText} onChange={(e)=>setSupportText(e.target.value.slice(0,2000))} placeholder="Напиши ответ пользователю…" rows={2}/><button disabled={busy||!supportText.trim()} aria-label="Отправить"><Icon name="send" size={19}/></button></form><div className="proSupportBottomActions"><span>{supportText.length}/2000</span><button type="button" onClick={()=>void action({action:"close_support",ticketId:selectedTicket})}>Закрыть обращение</button></div></>}</div></>:<div className="proSupportBlank"><Icon name="message" size={30}/><strong>Выбери обращение</strong><span>Переписка и данные пользователя откроются здесь.</span></div>}</section>

        <aside className="proTicketInspector">{detail&&selectedTicket?<><div className="proInspectorHead"><span>Обращение</span><strong>#{selectedTicket.slice(0,8)}</strong></div><dl><div><dt>Статус</dt><dd>{statusLabel(detail.ticket.status)}</dd></div><div><dt>Тема</dt><dd>{selectedTopic?.title??"Не выбрана"}</dd></div><div><dt>Создано</dt><dd>{date(detail.ticket.created_at)}</dd></div><div><dt>Вызов оператора</dt><dd>{date(detail.ticket.requested_at)}</dd></div><div><dt>Подключение</dt><dd>{date(detail.ticket.joined_at)}</dd></div></dl><div className="proInspectorUser"><span>Пользователь</span><strong>{selectedProfile?.first_name??"—"}</strong><small>{selectedProfile?.username?`@${selectedProfile.username}`:`TG ${selectedProfile?.telegram_id??"—"}`}</small></div></>:<div className="proEmpty">Нет выбранного обращения</div>}</aside>
      </div><details className="proSupportSettings"><summary><span><Icon name="edit" size={17}/>Автоответы поддержки</span><small>Редактирование сценариев</small></summary><div className="proTopicGrid">{(overview?.topics??[]).map((topic)=><TopicEditor key={topic.id} topic={topic} onSaved={loadOverview}/>)}</div></details></div>}

      {tab==="tradeup"&&<div className="proBroadcast"><section className="proBroadcastComposer"><div><h2>Новое сообщение</h2><p>Публикация появится в официальном чате и уведомлениях игроков.</p></div><form onSubmit={publish}><textarea value={announcement} onChange={(e)=>setAnnouncement(e.target.value.slice(0,4000))} placeholder="Напиши сообщение для игроков…" rows={5}/><div><span>{announcement.length}/4000</span><button disabled={busy||!announcement.trim()}>Опубликовать</button></div></form></section><section className="proBroadcastHistory"><div className="proSectionHead"><div><h2>История</h2><p>{overview?.announcements.length??0} публикаций</p></div></div>{(overview?.announcements??[]).map((item)=><article key={item.id} className={item.is_active?"":"disabled"}><header><strong>TradeUP</strong><time>{date(item.published_at)}</time></header><p>{item.body}</p><button type="button" onClick={()=>void action({action:"set_announcement_active",id:item.id,isActive:!item.is_active})}>{item.is_active?"Скрыть":"Вернуть"}</button></article>)}</section></div>}

      {tab==="users"&&<section className="proUsers"><div className="proUsersTools"><div><h2>Пользователи</h2><span>{overview?.users.length??0} загружено</span></div><label><Icon name="search" size={16}/><input value={userQuery} onChange={(e)=>setUserQuery(e.target.value)} placeholder="Имя, username или Telegram ID"/></label></div><div className="proUsersTable"><header><span>Пользователь</span><span>Баланс</span><span>Рейтинг</span><span>Сделки</span><span>Прибыль</span><span>Активность</span></header>{visibleUsers.map((user)=><div key={user.id}><div className="proUserIdentity"><span className="proTinyAvatar">{user.photo_url?<img src={user.photo_url} alt=""/>:user.first_name.charAt(0)}</span><span><strong>{user.first_name}</strong><small>{user.username?`@${user.username}`:`TG ${user.telegram_id}`}</small></span></div><span>{rub(user.balance)}</span><span>{user.rating}</span><span>{user.deals_count}</span><span>{rub(user.total_profit)}</span><time>{date(user.last_seen_at)}</time></div>)}</div></section>}
    </section>
  </main>;
}
