"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { useSearchParams } from "next/navigation";
import Icon from "@/components/icon";
import ProductImage from "@/components/product-image";
import { useTelegramSession } from "@/components/telegram-session";
import { rubles } from "@/lib/product";

type Tab = "overview" | "wanted" | "auctions" | "bundles" | "collections";
type ItemType = { id:string; slug?:string; name:string; brand:string|null; category_id:string; base_value:number|string; image_url:string|null };
type InventoryItem = { id:string; item_type_id:string; condition:number; specs:Record<string,unknown>; is_locked:boolean; acquired_price:number|string; serial_code?:string; item_types:ItemType|ItemType[]|null };
type Wanted = { id:string; buyer_id:string; item_type_id:string; budget_max:number|string; min_condition:number; min_storage_gb:number|null; min_battery_health:number|null; note:string; status:string; created_at:string; expires_at:string; item_types:ItemType|ItemType[]|null; profiles?:{id:string;first_name:string;username:string|null;photo_url:string|null;rating:number;deals_count:number}|null };
type MarketStat = { item_type_id:string; name:string; brand:string|null; category_id:string; sales_7d:number; sales_30d:number; median_7d:number|string|null; median_30d:number|string|null; median_prev_7d:number|string|null; low_30d:number|string|null; high_30d:number|string|null; avg_sell_seconds:number|string|null; active_listings:number; circulating:number };
type Auction = { id:string; listing_id:string; seller_id:string; start_price:number|string; current_bid:number|string|null; high_bidder_id:string|null; bid_count:number; status:string; ends_at:string };
type Listing = { id:string; inventory_item_id:string; title:string; price:number|string; status:string };
type Profile = { id:string; first_name:string; username:string|null; photo_url:string|null; rating:number; deals_count:number };
type Bundle = { id:string; seller_id:string; title:string; description:string; price:number|string; status:string; created_at:string };
type BundleItem = { bundle_id:string; item_id:string };
type CollectionSet = { id:string; name:string; description:string; sort_order:number };
type CollectionEntry = { set_id:string; item_type_id:string; item_types:ItemType|ItemType[]|null };

const tabs:{id:Tab;label:string;icon:"trend"|"search"|"trophy"|"package"|"collectible"}[]=[
 {id:"overview",label:"Пульс",icon:"trend"},{id:"wanted",label:"Ищу",icon:"search"},{id:"auctions",label:"Аукционы",icon:"trophy"},{id:"bundles",label:"Лоты",icon:"package"},{id:"collections",label:"Коллекции",icon:"collectible"},
];
const goalMeta:Record<string,{title:string;hint:string;xp:number}>={first_sale:{title:"Закрыть продажу",hint:"Продай любой предмет сегодня",xp:80},margin_8:{title:"Маржа 8%+",hint:"Закрой сделку с маржой не ниже 8%",xp:120},fast_sale:{title:"Быстрый оборот",hint:"Продай предмет менее чем за 30 минут",xp:100},negotiate:{title:"Договориться",hint:"Закрой сделку через торг",xp:90}};
function one<T>(value:T|T[]|null|undefined){return Array.isArray(value)?value[0]??null:value??null;}
function pct(now:number|string|null,prev:number|string|null){const a=Number(now),b=Number(prev);if(!Number.isFinite(a)||!Number.isFinite(b)||b===0)return null;return((a-b)/b)*100;}
function duration(seconds:number|string|null){const s=Number(seconds);if(!Number.isFinite(s)||s<=0)return "нет данных";if(s<3600)return `${Math.max(1,Math.round(s/60))} мин`;if(s<86400)return `${Math.round(s/3600)} ч`;return `${Math.round(s/86400)} дн`;}
function remaining(value:string){const ms=new Date(value).getTime()-Date.now();if(ms<=0)return "завершается";const min=Math.ceil(ms/60000);if(min<60)return `${min} мин`;const h=Math.ceil(min/60);if(h<24)return `${h} ч`;return `${Math.ceil(h/24)} дн`;}

export default function ExploreCenter(){
 const session=useTelegramSession();const params=useSearchParams();const requested=params.get("tab") as Tab|null;const[tab,setTab]=useState<Tab>(tabs.some(x=>x.id===requested)?requested!:"overview");
 const[overview,setOverview]=useState<Record<string,unknown>|null>(null);const[wanted,setWanted]=useState<{own:Wanted[];requests:Wanted[];itemTypes:ItemType[];inventory:InventoryItem[]}|null>(null);const[auctionData,setAuctionData]=useState<{auctions:Auction[];listings:Listing[];items:InventoryItem[];profiles:Profile[]}|null>(null);const[bundleData,setBundleData]=useState<{bundles:Bundle[];bundleItems:BundleItem[];items:InventoryItem[];profiles:Profile[]}|null>(null);const[collectionData,setCollectionData]=useState<{sets:CollectionSet[];entries:CollectionEntry[];currentTypeIds:string[];everTypeIds:string[]}|null>(null);
 const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);const[showCreate,setShowCreate]=useState(false);
 const[wantedType,setWantedType]=useState("");const[wantedBudget,setWantedBudget]=useState("");const[wantedCondition,setWantedCondition]=useState("75");
 const[auctionItem,setAuctionItem]=useState("");const[auctionPrice,setAuctionPrice]=useState("");const[auctionHours,setAuctionHours]=useState("24");const[bidAmounts,setBidAmounts]=useState<Record<string,string>>({});
 const[bundleItems,setBundleItems]=useState<string[]>([]);const[bundleTitle,setBundleTitle]=useState("");const[bundlePrice,setBundlePrice]=useState("");
 const load=useCallback(async(target:Tab,force=false)=>{if(session.state!=="verified")return;setError(null);setLoading(true);try{if(target==="overview"&&(force||!overview))setOverview(await session.callDepthAction("overview"));if(target==="wanted"&&(force||!wanted)){const r=await session.callDepthAction("wanted");setWanted({own:(r.own??[]) as Wanted[],requests:(r.requests??[]) as Wanted[],itemTypes:(r.itemTypes??[]) as ItemType[],inventory:(r.inventory??[]) as InventoryItem[]});}if(target==="auctions"&&(force||!auctionData)){const [a,w]=await Promise.all([session.callDepthAction("auctions"),wanted?Promise.resolve(null):session.callDepthAction("wanted")]);setAuctionData({auctions:(a.auctions??[]) as Auction[],listings:(a.listings??[]) as Listing[],items:(a.items??[]) as InventoryItem[],profiles:(a.profiles??[]) as Profile[]});if(w)setWanted({own:(w.own??[]) as Wanted[],requests:(w.requests??[]) as Wanted[],itemTypes:(w.itemTypes??[]) as ItemType[],inventory:(w.inventory??[]) as InventoryItem[]});}if(target==="bundles"&&(force||!bundleData)){const [b,w]=await Promise.all([session.callDepthAction("bundles"),wanted?Promise.resolve(null):session.callDepthAction("wanted")]);setBundleData({bundles:(b.bundles??[]) as Bundle[],bundleItems:(b.bundleItems??[]) as BundleItem[],items:(b.items??[]) as InventoryItem[],profiles:(b.profiles??[]) as Profile[]});if(w)setWanted({own:(w.own??[]) as Wanted[],requests:(w.requests??[]) as Wanted[],itemTypes:(w.itemTypes??[]) as ItemType[],inventory:(w.inventory??[]) as InventoryItem[]});}if(target==="collections"&&(force||!collectionData)){const c=await session.callDepthAction("collections");setCollectionData({sets:(c.sets??[]) as CollectionSet[],entries:(c.entries??[]) as CollectionEntry[],currentTypeIds:(c.currentTypeIds??[]) as string[],everTypeIds:(c.everTypeIds??[]) as string[]});}}catch(e){setError(e instanceof Error?e.message:"Не удалось загрузить раздел");}finally{setLoading(false);}},[session,overview,wanted,auctionData,bundleData,collectionData]);
 useEffect(()=>{if(session.state==="verified")void load(tab);else if(["browser","unavailable","error"].includes(session.state))setLoading(false);},[session.state,tab,load]);
 function changeTab(next:Tab){setTab(next);setShowCreate(false);}
 async function claimGoal(key:string){setBusy(true);try{await session.callDepthAction("claim_goal",{goalKey:key});await load("overview",true);}catch(e){setError(e instanceof Error&&e.message==="goal_already_claimed"?"Цель уже получена":"Цель ещё не выполнена");}finally{setBusy(false);}}
 async function createWanted(e:React.FormEvent){e.preventDefault();if(!wantedType||!wantedBudget)return;setBusy(true);try{await session.callDepthAction("create_wanted",{itemTypeId:wantedType,budgetMax:Number(wantedBudget),minCondition:Number(wantedCondition)});setWantedBudget("");setShowCreate(false);await load("wanted",true);}catch(e){setError(e instanceof Error?e.message:"Не удалось создать запрос");}finally{setBusy(false);}}
 async function cancelWanted(id:string){setBusy(true);try{await session.callDepthAction("cancel_wanted",{requestId:id});await load("wanted",true);}finally{setBusy(false);}}
 async function createAuction(e:React.FormEvent){e.preventDefault();const item=wanted?.inventory.find(x=>x.id===auctionItem);const type=one(item?.item_types);if(!item||!type||!auctionPrice)return;setBusy(true);try{await session.callDepthAction("create_auction",{itemId:item.id,title:type.name,startPrice:Number(auctionPrice),durationMinutes:Number(auctionHours)*60});setShowCreate(false);setAuctionItem("");setAuctionPrice("");await load("auctions",true);}catch(e){setError(e instanceof Error?e.message:"Не удалось создать аукцион");}finally{setBusy(false);}}
 async function bidAuction(id:string){const amount=Number(bidAmounts[id]);if(!amount)return;setBusy(true);try{await session.callDepthAction("bid_auction",{auctionId:id,amount});setBidAmounts(x=>({...x,[id]:""}));await load("auctions",true);}catch(e){const code=e instanceof Error?e.message:"";setError(code==="bid_too_low"?"Ставка слишком низкая":code==="insufficient_funds"?"Недостаточно средств":code||"Ставка не прошла");}finally{setBusy(false);}}
 async function createBundle(e:React.FormEvent){e.preventDefault();if(bundleItems.length<2||!bundleTitle.trim()||!bundlePrice)return;setBusy(true);try{await session.callDepthAction("create_bundle",{itemIds:bundleItems,title:bundleTitle,description:"Комплект из личного инвентаря",price:Number(bundlePrice)});setBundleItems([]);setBundleTitle("");setBundlePrice("");setShowCreate(false);await load("bundles",true);}catch(e){setError(e instanceof Error?e.message:"Не удалось создать лот");}finally{setBusy(false);}}
 async function buyBundle(id:string){setBusy(true);try{await session.callDepthAction("buy_bundle",{bundleId:id});await load("bundles",true);}catch(e){setError(e instanceof Error&&e.message==="insufficient_funds"?"Недостаточно средств":"Покупка не прошла");}finally{setBusy(false);}}
 if(session.state!=="verified"&&!loading)return <div className="flatAuth"><Icon name="trend" size={30}/><strong>Рынок+ доступен в Telegram</strong><button onClick={session.openBot}>Открыть TradeUP</button></div>;
 const marketStats=(overview?.marketStats??[]) as MarketStat[];const goals=(overview?.goalDone??{}) as Record<string,boolean>;const claims=new Set(((overview?.goalClaims??[]) as {goal_key:string}[]).map(x=>x.goal_key));const chains=(overview?.chains??[]) as {id:string;start_capital:number|string;current_capital:number|string;trade_count:number;total_profit:number|string;is_active:boolean}[];const season=overview?.season as {name:string;ends_at:string}|null|undefined;const seasonStats=overview?.seasonStats as {profit:number|string;volume:number|string;sales:number;purchases:number;best_margin_pct:number|string}|null|undefined;const highlight=overview?.highlight as {profit:number|string;profit_pct:number|string;item?:InventoryItem;profile?:{first_name:string;username:string|null}}|null|undefined;
 const listingMap=useMemo(()=>new Map((auctionData?.listings??[]).map(x=>[x.id,x])),[auctionData]);const auctionItemMap=useMemo(()=>new Map((auctionData?.items??[]).map(x=>[x.id,x])),[auctionData]);const bundleItemMap=useMemo(()=>new Map((bundleData?.items??[]).map(x=>[x.id,x])),[bundleData]);
 return <div className="depthPage">
  <header className="depthHeader"><div><span>Рынок+</span><h1>Живой рынок</h1></div><Link href="/" aria-label="На рынок"><Icon name="arrowLeft"/></Link></header>
  <nav className="depthTabs">{tabs.map(t=><button key={t.id} className={tab===t.id?"active":""} onClick={()=>changeTab(t.id)}><Icon name={t.icon} size={17}/><span>{t.label}</span></button>)}</nav>
  {error&&<div className="depthError">{error}<button onClick={()=>setError(null)}><Icon name="close" size={14}/></button></div>}
  {loading&&<div className="depthLoading"><i/><i/><i/></div>}

  {!loading&&tab==="overview"&&<div className="depthContent">
   {highlight&&<section className="depthHero"><span>Сделка дня</span><strong>+{rubles(highlight.profit)} · +{Number(highlight.profit_pct).toFixed(1)}%</strong><p>{one(highlight.item?.item_types)?.name??"Предмет"} · {highlight.profile?.first_name??"Игрок"}</p></section>}
   <section className="depthSection"><div className="depthSectionTitle"><div><span>Рынок сейчас</span><h2>Что реально продаётся</h2></div></div><div className="marketPulseList">{marketStats.slice(0,10).map(s=>{const change=pct(s.median_7d,s.median_prev_7d);return <div className="marketPulseRow" key={s.item_type_id}><div><strong>{s.name}</strong><span>{s.sales_7d} продаж за 7 дней · обычно {duration(s.avg_sell_seconds)}</span></div><div><strong>{s.median_7d?rubles(s.median_7d):"Нет цены"}</strong>{change!==null&&<span className={change>=0?"up":"down"}>{change>=0?"+":""}{change.toFixed(1)}%</span>}</div></div>;})}{!marketStats.length&&<div className="depthEmpty">Рынок только начинает собирать статистику. Здесь не будет выдуманных цен.</div>}</div></section>
   <section className="depthSection"><div className="depthSectionTitle"><div><span>Сегодня</span><h2>Цели перекупа</h2></div><div className="depthLevel">LVL {Number((overview?.progress as {level?:number})?.level??1)}</div></div><div className="goalList">{Object.entries(goalMeta).map(([key,g])=>{const done=Boolean(goals[key]),claimed=claims.has(key);return <div className="goalRow" key={key}><div className={done?"goalCheck done":"goalCheck"}>{done?<Icon name="check" size={15}/>:<span/>}</div><div><strong>{g.title}</strong><span>{g.hint}</span></div><button disabled={!done||claimed||busy} onClick={()=>void claimGoal(key)}>{claimed?"Получено":`+${g.xp} XP`}</button></div>;})}</div></section>
   {season&&<section className="depthSection"><div className="depthSectionTitle"><div><span>Сезон</span><h2>{season.name}</h2></div><span className="seasonEnd">ещё {remaining(season.ends_at)}</span></div><div className="seasonStats"><div><strong>{rubles(seasonStats?.profit??0)}</strong><span>прибыль</span></div><div><strong>{seasonStats?.sales??0}</strong><span>продаж</span></div><div><strong>{Number(seasonStats?.best_margin_pct??0).toFixed(1)}%</strong><span>лучшая маржа</span></div></div><p className="depthHint">Сезон не вайпает деньги и предметы. Он фиксирует твою историю и даёт только статусные награды.</p></section>}
   <section className="depthSection"><div className="depthSectionTitle"><div><span>Flip Chain</span><h2>Цепочки перекупа</h2></div></div>{chains.length?<div className="chainList">{chains.map((c,i)=><div className="chainRow" key={c.id}><span>#{i+1}</span><div><strong>{rubles(c.start_capital)} → {rubles(c.current_capital)}</strong><small>{c.trade_count} сделок · +{rubles(c.total_profit)}</small></div>{c.is_active&&<b>активна</b>}</div>)}</div>:<div className="depthEmpty">Первая прибыльная продажа запустит твою цепочку.</div>}</section>
  </div>}

  {!loading&&tab==="wanted"&&wanted&&<div className="depthContent"><div className="depthActionLine"><div><span>Обратный рынок</span><h2>Люди уже ищут товары</h2></div><button onClick={()=>setShowCreate(v=>!v)}><Icon name="plus" size={17}/>{showCreate?"Закрыть":"Создать запрос"}</button></div>{showCreate&&<form className="depthForm" onSubmit={createWanted}><label>Что ищешь<select value={wantedType} onChange={e=>setWantedType(e.target.value)} required><option value="">Выбери предмет</option>{wanted.itemTypes.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><div className="depthFormSplit"><label>Бюджет<input value={wantedBudget} onChange={e=>setWantedBudget(e.target.value.replace(/\D/g,""))} inputMode="numeric" placeholder="35000"/></label><label>Состояние от<input value={wantedCondition} onChange={e=>setWantedCondition(e.target.value.replace(/\D/g,""))} inputMode="numeric"/></label></div><button type="submit" disabled={busy}>Опубликовать запрос</button></form>}
   {wanted.own.length>0&&<section className="depthSection"><div className="depthSectionTitle"><div><span>Твои запросы</span><h2>Что ты ищешь</h2></div></div>{wanted.own.map(w=><div className="wantedRow" key={w.id}><div><strong>{one(w.item_types)?.name??"Предмет"}</strong><span>до {rubles(w.budget_max)} · состояние от {w.min_condition}%</span></div><b>{w.status}</b>{w.status==="active"&&<button onClick={()=>void cancelWanted(w.id)}>Снять</button>}</div>)}</section>}
   <section className="depthSection"><div className="depthSectionTitle"><div><span>Спрос</span><h2>Запросы покупателей</h2></div><strong>{wanted.requests.length}</strong></div>{wanted.requests.map(w=>{const match=wanted.inventory.find(i=>i.item_type_id===w.item_type_id&&i.condition>=w.min_condition&&Number(i.specs?.storage_gb??0)>=(w.min_storage_gb??0)&&Number(i.specs?.battery_health??0)>=(w.min_battery_health??0));return <div className="wantedRow public" key={w.id}><div><strong>{one(w.item_types)?.name??"Предмет"}</strong><span>{w.profiles?.first_name??"Покупатель"} · бюджет до {rubles(w.budget_max)} · {w.min_condition}%+</span></div>{match?<Link href={`/sell/new?item=${match.id}&wanted=${w.id}`}>Предложить свой</Link>:<small>нет подходящего в инвентаре</small>}</div>;})}{!wanted.requests.length&&<div className="depthEmpty">Активных запросов пока нет.</div>}</section>
  </div>}

  {!loading&&tab==="auctions"&&auctionData&&<div className="depthContent"><div className="depthActionLine"><div><span>Торги</span><h2>Аукционы игроков</h2></div><button onClick={()=>setShowCreate(v=>!v)}><Icon name="plus" size={17}/>{showCreate?"Закрыть":"Выставить"}</button></div>{showCreate&&<form className="depthForm" onSubmit={createAuction}><label>Предмет<select value={auctionItem} onChange={e=>setAuctionItem(e.target.value)} required><option value="">Из свободного инвентаря</option>{(wanted?.inventory??[]).map(i=><option value={i.id} key={i.id}>{one(i.item_types)?.name} · {i.condition}%</option>)}</select></label><div className="depthFormSplit"><label>Стартовая цена<input value={auctionPrice} onChange={e=>setAuctionPrice(e.target.value.replace(/\D/g,""))} inputMode="numeric"/></label><label>Длительность<select value={auctionHours} onChange={e=>setAuctionHours(e.target.value)}><option value="1">1 час</option><option value="6">6 часов</option><option value="24">24 часа</option><option value="72">3 дня</option><option value="168">7 дней</option></select></label></div><button disabled={busy}>Запустить аукцион</button></form>}
   <div className="auctionGrid">{auctionData.auctions.filter(a=>a.status==="active").map(a=>{const l=listingMap.get(a.listing_id);const item=l?auctionItemMap.get(l.inventory_item_id):null;const type=one(item?.item_types);const mine=a.seller_id===session.profile?.id;const min=Math.round(Number(a.current_bid??a.start_price)+(a.current_bid?Math.max(100,Number(a.current_bid)*.02):0));return <article className="auctionTile" key={a.id}><div className="auctionImage"><ProductImage src={type?.image_url} alt={type?.name??l?.title??"Аукцион"} categoryId={type?.category_id??""}/><span>{remaining(a.ends_at)}</span></div><div className="auctionInfo"><strong>{l?.title??type?.name??"Предмет"}</strong><span>{a.bid_count} ставок · {item?.condition??0}%</span><div className="auctionPrice"><small>{a.current_bid?"Текущая ставка":"Старт"}</small><b>{rubles(a.current_bid??a.start_price)}</b></div>{!mine&&<div className="auctionBid"><input value={bidAmounts[a.id]??""} onChange={e=>setBidAmounts(x=>({...x,[a.id]:e.target.value.replace(/\D/g,"")}))} placeholder={String(min)} inputMode="numeric"/><button disabled={busy} onClick={()=>void bidAuction(a.id)}>Ставка</button></div>}{mine&&<small className="auctionMine">Твой аукцион</small>}</div></article>;})}</div>{!auctionData.auctions.some(a=>a.status==="active")&&<div className="depthEmpty">Активных аукционов пока нет. Первый можно запустить из своего инвентаря.</div>}
  </div>}

  {!loading&&tab==="bundles"&&bundleData&&<div className="depthContent"><div className="depthActionLine"><div><span>Лоты</span><h2>Купить комплект и разобрать</h2></div><button onClick={()=>setShowCreate(v=>!v)}><Icon name="plus" size={17}/>{showCreate?"Закрыть":"Собрать лот"}</button></div>{showCreate&&<form className="depthForm" onSubmit={createBundle}><label>Название<input value={bundleTitle} onChange={e=>setBundleTitle(e.target.value.slice(0,100))} placeholder="Комплект Apple для перепродажи"/></label><div className="bundlePicker">{(wanted?.inventory??[]).map(i=>{const type=one(i.item_types),checked=bundleItems.includes(i.id);return <button type="button" key={i.id} className={checked?"selected":""} onClick={()=>setBundleItems(x=>checked?x.filter(id=>id!==i.id):x.length<5?[...x,i.id]:x)}><span>{type?.name}</span><small>{i.condition}% · {rubles(i.acquired_price)}</small><Icon name={checked?"check":"plus"} size={15}/></button>;})}</div><label>Цена комплекта<input value={bundlePrice} onChange={e=>setBundlePrice(e.target.value.replace(/\D/g,""))} inputMode="numeric"/></label><button disabled={busy||bundleItems.length<2}>Опубликовать {bundleItems.length}/5</button></form>}
   <div className="bundleList">{bundleData.bundles.filter(b=>b.status==="active").map(b=>{const links=bundleData.bundleItems.filter(x=>x.bundle_id===b.id);const items=links.map(x=>bundleItemMap.get(x.item_id)).filter(Boolean) as InventoryItem[];const mine=b.seller_id===session.profile?.id;return <article className="bundleRow" key={b.id}><div className="bundleThumbStack">{items.slice(0,3).map((i,index)=>{const t=one(i.item_types);return <span key={i.id} style={{zIndex:3-index}}><ProductImage src={t?.image_url} alt={t?.name??""} categoryId={t?.category_id??""}/></span>;})}</div><div><strong>{b.title}</strong><span>{items.map(i=>one(i.item_types)?.name).filter(Boolean).slice(0,3).join(" · ")}</span><small>{items.length} предмета</small></div><div className="bundleBuy"><strong>{rubles(b.price)}</strong>{mine?<small>твой лот</small>:<button disabled={busy} onClick={()=>void buyBundle(b.id)}>Купить</button>}</div></article>;})}</div>{!bundleData.bundles.some(b=>b.status==="active")&&<div className="depthEmpty">Лотов пока нет. Хороший лот позволяет купить комплект дешевле и распродать его по частям.</div>}
  </div>}

  {!loading&&tab==="collections"&&collectionData&&<div className="depthContent"><div className="depthActionLine"><div><span>История владения</span><h2>Коллекции</h2></div></div><div className="collectionList">{collectionData.sets.map(set=>{const entries=collectionData.entries.filter(x=>x.set_id===set.id),ever=entries.filter(x=>collectionData.everTypeIds.includes(x.item_type_id)),current=entries.filter(x=>collectionData.currentTypeIds.includes(x.item_type_id));const progress=entries.length?Math.round(ever.length/entries.length*100):0;return <section className="collectionRow" key={set.id}><div className="collectionTop"><div><strong>{set.name}</strong><span>{set.description}</span></div><b>{ever.length}/{entries.length}</b></div><div className="collectionTrack"><i style={{width:`${progress}%`}}/></div><div className="collectionItems">{entries.map(e=>{const type=one(e.item_types),owned=current.some(x=>x.item_type_id===e.item_type_id),had=collectionData.everTypeIds.includes(e.item_type_id);return <div key={e.item_type_id} className={owned?"owned":had?"historic":""}><span><ProductImage src={type?.image_url} alt={type?.name??""} categoryId={type?.category_id??""}/></span><small>{type?.name}</small>{owned?<b>есть</b>:had?<b>был</b>:null}</div>;})}</div></section>;})}</div></div>}
 </div>;
}
