alter table public.listings drop constraint if exists listings_status_check;
alter table public.listings add constraint listings_status_check check(status in('active','reserved','sold','cancelled','auction','expired'));

create table if not exists public.auctions(
 id uuid primary key default gen_random_uuid(),listing_id uuid not null unique references public.listings(id) on delete cascade,seller_id uuid not null references public.profiles(id) on delete cascade,
 start_price numeric(12,2) not null check(start_price>0),current_bid numeric(12,2),high_bidder_id uuid references public.profiles(id) on delete set null,
 bid_count integer not null default 0,status text not null default 'active' check(status in('active','sold','expired','cancelled')),ends_at timestamptz not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.auction_bids(id uuid primary key default gen_random_uuid(),auction_id uuid not null references public.auctions(id) on delete cascade,bidder_id uuid not null references public.profiles(id) on delete cascade,amount numeric(12,2) not null check(amount>0),created_at timestamptz not null default now());
create index if not exists auctions_active_end_idx on public.auctions(ends_at) where status='active'; create index if not exists auction_bids_auction_idx on public.auction_bids(auction_id,created_at desc); create index if not exists auction_bids_bidder_idx on public.auction_bids(bidder_id,created_at desc);
alter table public.auctions enable row level security; alter table public.auction_bids enable row level security; revoke all on public.auctions,public.auction_bids from anon,authenticated;

create or replace function public.create_auction_atomic(p_seller_id uuid,p_item_id uuid,p_title text,p_start_price numeric,p_duration_minutes integer default 1440) returns uuid language plpgsql security definer set search_path=public,pg_temp as $$
declare it public.inventory_items%rowtype; lid uuid; aid uuid; dur integer;
begin
 dur:=greatest(10,least(coalesce(p_duration_minutes,1440),10080)); select * into it from public.inventory_items where id=p_item_id for update; if not found or it.owner_id<>p_seller_id then raise exception 'item_not_owned'; end if; if it.is_locked then raise exception 'item_locked'; end if; if char_length(trim(coalesce(p_title,'')))<3 or char_length(trim(p_title))>100 then raise exception 'invalid_title'; end if; if p_start_price is null or p_start_price<=0 then raise exception 'invalid_price'; end if;
 update public.inventory_items set is_locked=true where id=p_item_id;
 insert into public.listings(seller_id,inventory_item_id,title,description,price,status) values(p_seller_id,p_item_id,trim(p_title),'Аукцион TradeUP',round(p_start_price,0),'auction') returning id into lid;
 insert into public.auctions(listing_id,seller_id,start_price,ends_at) values(lid,p_seller_id,round(p_start_price,0),now()+make_interval(mins=>dur)) returning id into aid; return aid;
end $$;

create or replace function public.settle_auction_atomic(p_auction_id uuid) returns uuid language plpgsql security definer set search_path=public,pg_temp as $$
declare a public.auctions%rowtype; l public.listings%rowtype; it public.inventory_items%rowtype; fee numeric; net numeric; profit numeric; tid uuid;
begin
 select * into a from public.auctions where id=p_auction_id for update; if not found then raise exception 'auction_not_found'; end if; if a.status<>'active' then return null; end if; if a.ends_at>now() then raise exception 'auction_not_ended'; end if;
 select * into l from public.listings where id=a.listing_id for update; select * into it from public.inventory_items where id=l.inventory_item_id for update;
 if a.high_bidder_id is null then update public.auctions set status='expired',updated_at=now() where id=a.id; update public.listings set status='expired',updated_at=now() where id=l.id; update public.inventory_items set is_locked=false where id=it.id; return null; end if;
 perform 1 from public.profiles where id in(a.high_bidder_id,a.seller_id) order by id for update; fee:=round(a.current_bid*.04,0); net:=a.current_bid-fee; profit:=net-it.acquired_price;
 update public.profiles set deals_count=deals_count+1,rating=rating+2,updated_at=now() where id=a.high_bidder_id;
 update public.profiles set balance=balance+net,deals_count=deals_count+1,rating=rating+3,total_profit=total_profit+profit,updated_at=now() where id=a.seller_id;
 update public.inventory_items set owner_id=a.high_bidder_id,acquired_price=a.current_bid,acquired_at=now(),is_locked=false where id=it.id;
 update public.listings set status='sold',price=a.current_bid,updated_at=now() where id=l.id; update public.auctions set status='sold',updated_at=now() where id=a.id;
 insert into public.trades(listing_id,item_id,seller_id,buyer_id,amount,fee,seller_profit) values(l.id,it.id,a.seller_id,a.high_bidder_id,a.current_bid,fee,profit) returning id into tid; insert into public.price_history(item_type_id,price) values(it.item_type_id,a.current_bid); return tid;
end $$;

create or replace function public.place_auction_bid_atomic(p_bidder_id uuid,p_auction_id uuid,p_amount numeric) returns numeric language plpgsql security definer set search_path=public,pg_temp as $$
declare a public.auctions%rowtype; l public.listings%rowtype; min_bid numeric; bal numeric; delta numeric;
begin
 select * into a from public.auctions where id=p_auction_id for update; if not found or a.status<>'active' then raise exception 'auction_not_active'; end if; if a.ends_at<=now() then perform public.settle_auction_atomic(a.id); raise exception 'auction_ended'; end if;
 select * into l from public.listings where id=a.listing_id; if l.seller_id=p_bidder_id then raise exception 'cannot_bid_own_auction'; end if;
 min_bid:=case when a.current_bid is null then a.start_price else a.current_bid+greatest(100,round(a.current_bid*.02,0)) end; if p_amount is null or p_amount<min_bid then raise exception 'bid_too_low'; end if;
 perform 1 from public.profiles where id in(p_bidder_id,a.high_bidder_id) order by id for update; select balance into bal from public.profiles where id=p_bidder_id;
 if a.high_bidder_id=p_bidder_id then delta:=p_amount-a.current_bid; if bal<delta then raise exception 'insufficient_funds'; end if; update public.profiles set balance=balance-delta,updated_at=now() where id=p_bidder_id;
 else if bal<p_amount then raise exception 'insufficient_funds'; end if; update public.profiles set balance=balance-p_amount,updated_at=now() where id=p_bidder_id; if a.high_bidder_id is not null then update public.profiles set balance=balance+a.current_bid,updated_at=now() where id=a.high_bidder_id; insert into public.notifications(user_id,type,title,body,href,event_key) values(a.high_bidder_id,'auction','Твою ставку перебили',l.title||' · новая ставка '||round(p_amount,0)||' ₽','/explore?tab=auctions','auction_outbid:'||a.id||':'||(a.bid_count+1)) on conflict(event_key) do nothing; end if; end if;
 update public.auctions set current_bid=round(p_amount,0),high_bidder_id=p_bidder_id,bid_count=bid_count+1,ends_at=case when ends_at-now()<=interval '30 seconds' then ends_at+interval '30 seconds' else ends_at end,updated_at=now() where id=a.id;
 insert into public.auction_bids(auction_id,bidder_id,amount) values(a.id,p_bidder_id,round(p_amount,0)); insert into public.notifications(user_id,type,title,body,href,event_key) values(a.seller_id,'auction','Новая ставка',l.title||' · '||round(p_amount,0)||' ₽','/explore?tab=auctions','auction_bid:'||a.id||':'||(a.bid_count+1)) on conflict(event_key) do nothing; return round(p_amount,0);
end $$;

create or replace function public.settle_due_auctions(p_limit integer default 25) returns integer language plpgsql security definer set search_path=public as $$ declare r record; n integer:=0; begin for r in select id from public.auctions where status='active' and ends_at<=now() order by ends_at limit greatest(1,least(coalesce(p_limit,25),100)) loop perform public.settle_auction_atomic(r.id); n:=n+1; end loop; return n; end $$;

create table if not exists public.bundles(id uuid primary key default gen_random_uuid(),seller_id uuid not null references public.profiles(id) on delete cascade,title text not null check(char_length(title) between 3 and 100),description text not null default '' check(char_length(description)<=1000),price numeric(12,2) not null check(price>0),status text not null default 'active' check(status in('active','sold','cancelled')),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.bundle_items(bundle_id uuid not null references public.bundles(id) on delete cascade,item_id uuid not null unique references public.inventory_items(id) on delete restrict,primary key(bundle_id,item_id));
create table if not exists public.bundle_sales(id uuid primary key default gen_random_uuid(),bundle_id uuid not null unique references public.bundles(id) on delete restrict,seller_id uuid not null references public.profiles(id),buyer_id uuid not null references public.profiles(id),amount numeric(12,2) not null,fee numeric(12,2) not null,profit numeric(12,2) not null,completed_at timestamptz not null default now());
create index if not exists bundles_seller_idx on public.bundles(seller_id,created_at desc); create index if not exists bundle_sales_buyer_idx on public.bundle_sales(buyer_id,completed_at desc);
alter table public.bundles enable row level security; alter table public.bundle_items enable row level security; alter table public.bundle_sales enable row level security; revoke all on public.bundles,public.bundle_items,public.bundle_sales from anon,authenticated;

create or replace function public.create_bundle_atomic(p_seller_id uuid,p_item_ids uuid[],p_title text,p_description text,p_price numeric) returns uuid language plpgsql security definer set search_path=public,pg_temp as $$ declare bid uuid; cnt integer; begin
 cnt:=coalesce(array_length(p_item_ids,1),0); if cnt<2 or cnt>5 then raise exception 'invalid_bundle_size'; end if; if (select count(distinct x) from unnest(p_item_ids) x)<>cnt then raise exception 'duplicate_bundle_item'; end if; if p_price<=0 then raise exception 'invalid_price'; end if;
 perform 1 from public.inventory_items where id=any(p_item_ids) order by id for update; if (select count(*) from public.inventory_items where id=any(p_item_ids) and owner_id=p_seller_id and not is_locked)<>cnt then raise exception 'bundle_item_unavailable'; end if;
 insert into public.bundles(seller_id,title,description,price) values(p_seller_id,trim(p_title),left(coalesce(p_description,''),1000),round(p_price,0)) returning id into bid; insert into public.bundle_items(bundle_id,item_id) select bid,unnest(p_item_ids); update public.inventory_items set is_locked=true where id=any(p_item_ids); return bid; end $$;

create or replace function public.cancel_bundle_atomic(p_seller_id uuid,p_bundle_id uuid) returns boolean language plpgsql security definer set search_path=public,pg_temp as $$ declare ids uuid[]; begin select array_agg(item_id) into ids from public.bundle_items where bundle_id=p_bundle_id; update public.bundles set status='cancelled',updated_at=now() where id=p_bundle_id and seller_id=p_seller_id and status='active'; if not found then return false; end if; update public.inventory_items set is_locked=false where id=any(ids); return true; end $$;

create or replace function public.buy_bundle_atomic(p_buyer_id uuid,p_bundle_id uuid) returns uuid language plpgsql security definer set search_path=public,pg_temp as $$
declare b public.bundles%rowtype; bal numeric; fee numeric; net numeric; total_old numeric; profit numeric; sid uuid; r record; piece numeric;
begin select * into b from public.bundles where id=p_bundle_id for update; if not found or b.status<>'active' then raise exception 'bundle_not_active'; end if; if b.seller_id=p_buyer_id then raise exception 'cannot_buy_own_bundle'; end if; perform 1 from public.profiles where id in(p_buyer_id,b.seller_id) order by id for update; select balance into bal from public.profiles where id=p_buyer_id; if bal<b.price then raise exception 'insufficient_funds'; end if; perform 1 from public.inventory_items i join public.bundle_items bi on bi.item_id=i.id where bi.bundle_id=b.id order by i.id for update; if exists(select 1 from public.inventory_items i join public.bundle_items bi on bi.item_id=i.id where bi.bundle_id=b.id and i.owner_id<>b.seller_id) then raise exception 'inventory_mismatch'; end if;
 select sum(i.acquired_price) into total_old from public.inventory_items i join public.bundle_items bi on bi.item_id=i.id where bi.bundle_id=b.id; fee:=round(b.price*.04,0); net:=b.price-fee; profit:=net-total_old;
 update public.profiles set balance=balance-b.price,deals_count=deals_count+1,rating=rating+2,updated_at=now() where id=p_buyer_id; update public.profiles set balance=balance+net,deals_count=deals_count+1,rating=rating+3,total_profit=total_profit+profit,updated_at=now() where id=b.seller_id;
 insert into public.bundle_sales(bundle_id,seller_id,buyer_id,amount,fee,profit) values(b.id,b.seller_id,p_buyer_id,b.price,fee,profit) returning id into sid;
 for r in select i.*,it.base_value from public.inventory_items i join public.bundle_items bi on bi.item_id=i.id join public.item_types it on it.id=i.item_type_id where bi.bundle_id=b.id loop piece:=round(b.price*(r.base_value/(select sum(it2.base_value) from public.bundle_items bx join public.inventory_items ix on ix.id=bx.item_id join public.item_types it2 on it2.id=ix.item_type_id where bx.bundle_id=b.id)),0); insert into public.item_events(item_id,event_type,actor_id,counterparty_id,amount,meta) values(r.id,'sale',b.seller_id,p_buyer_id,piece,jsonb_build_object('bundle_sale_id',sid,'bundle_id',b.id)); update public.inventory_items set owner_id=p_buyer_id,acquired_price=piece,acquired_at=now(),is_locked=false,owner_count=owner_count+1,lifetime_turnover=lifetime_turnover+piece,last_sale_price=piece where id=r.id; insert into public.price_history(item_type_id,price) values(r.item_type_id,piece); end loop;
 update public.bundles set status='sold',updated_at=now() where id=b.id; return sid; end $$;

create table if not exists public.seasons(id uuid primary key default gen_random_uuid(),slug text not null unique,name text not null,starts_at timestamptz not null,ends_at timestamptz not null,is_active boolean not null default true);
create table if not exists public.profile_season_stats(season_id uuid not null references public.seasons(id) on delete cascade,profile_id uuid not null references public.profiles(id) on delete cascade,volume numeric(14,2) not null default 0,profit numeric(14,2) not null default 0,purchases integer not null default 0,sales integer not null default 0,best_margin_pct numeric(8,2) not null default 0,unique_item_types uuid[] not null default '{}'::uuid[],updated_at timestamptz not null default now(),primary key(season_id,profile_id));
insert into public.seasons(slug,name,starts_at,ends_at,is_active) values('season-1','Первый миллион',date_trunc('month',now()),date_trunc('month',now())+interval '3 months',true) on conflict(slug) do nothing;
alter table public.seasons enable row level security; alter table public.profile_season_stats enable row level security; revoke all on public.seasons,public.profile_season_stats from anon,authenticated;

create table if not exists public.profile_progress(profile_id uuid primary key references public.profiles(id) on delete cascade,xp integer not null default 0,level integer not null default 1,updated_at timestamptz not null default now());
create table if not exists public.goal_events(id uuid primary key default gen_random_uuid(),profile_id uuid not null references public.profiles(id) on delete cascade,event_type text not null,value numeric not null default 1,meta jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create table if not exists public.goal_claims(profile_id uuid not null references public.profiles(id) on delete cascade,goal_key text not null,goal_date date not null default current_date,xp_awarded integer not null,claimed_at timestamptz not null default now(),primary key(profile_id,goal_key,goal_date)); create index if not exists goal_events_profile_day_idx on public.goal_events(profile_id,created_at desc);
alter table public.profile_progress enable row level security; alter table public.goal_events enable row level security; alter table public.goal_claims enable row level security; revoke all on public.profile_progress,public.goal_events,public.goal_claims from anon,authenticated;

create table if not exists public.flip_chains(id uuid primary key default gen_random_uuid(),profile_id uuid not null references public.profiles(id) on delete cascade,start_capital numeric(12,2) not null,current_capital numeric(12,2) not null,trade_count integer not null default 0,total_profit numeric(12,2) not null default 0,is_active boolean not null default true,started_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.flip_chain_steps(id uuid primary key default gen_random_uuid(),chain_id uuid not null references public.flip_chains(id) on delete cascade,trade_id uuid not null unique references public.trades(id) on delete cascade,buy_price numeric(12,2) not null,sell_price numeric(12,2) not null,profit numeric(12,2) not null,created_at timestamptz not null default now()); create index if not exists flip_chains_profile_idx on public.flip_chains(profile_id,updated_at desc);
alter table public.flip_chains enable row level security; alter table public.flip_chain_steps enable row level security; revoke all on public.flip_chains,public.flip_chain_steps from anon,authenticated;

create table if not exists public.collection_sets(id text primary key,name text not null,description text not null,sort_order integer not null default 0);
create table if not exists public.collection_entries(set_id text not null references public.collection_sets(id) on delete cascade,item_type_id uuid not null references public.item_types(id) on delete cascade,primary key(set_id,item_type_id));
insert into public.collection_sets(id,name,description,sort_order) values('playstation','PlayStation Collection','Собери историю PlayStation и портативок Sony.',10),('apple-essentials','Apple Essentials','Классические устройства Apple из разных эпох.',20),('retro-gaming','Retro Gaming','Консоли и портативки прошлых поколений.',30),('sneaker-rotation','Sneaker Rotation','Знаковые пары для витрины перекупа.',40) on conflict(id) do update set name=excluded.name,description=excluded.description,sort_order=excluded.sort_order;
insert into public.collection_entries(set_id,item_type_id) select 'playstation',id from public.item_types where slug in('playstation-4-slim-used','playstation-5-slim','psp-3000') on conflict do nothing;
insert into public.collection_entries(set_id,item_type_id) select 'apple-essentials',id from public.item_types where slug in('iphone-13-128','iphone-14-pro','macbook-air-m2','apple-watch-se-used','ipad-air-5') on conflict do nothing;
insert into public.collection_entries(set_id,item_type_id) select 'retro-gaming',id from public.item_types where slug in('game-boy-color','game-boy-original-used','nintendo-gamecube','nintendo-wii','xbox-360','psp-3000') on conflict do nothing;
insert into public.collection_entries(set_id,item_type_id) select 'sneaker-rotation',id from public.item_types where slug in('air-jordan-1-high','dunk-low-panda','adidas-samba','yeezy-boost-350','new-balance-2002r') on conflict do nothing;
alter table public.collection_sets enable row level security; alter table public.collection_entries enable row level security; revoke all on public.collection_sets,public.collection_entries from anon,authenticated;

create table if not exists public.market_highlights(highlight_date date primary key,trade_id uuid not null references public.trades(id) on delete cascade,profile_id uuid not null references public.profiles(id) on delete cascade,item_id uuid not null references public.inventory_items(id) on delete cascade,profit numeric(12,2) not null,profit_pct numeric(8,2) not null,updated_at timestamptz not null default now());
alter table public.market_highlights enable row level security; revoke all on public.market_highlights from anon,authenticated;

create or replace function public.after_trade_progression() returns trigger language plpgsql security definer set search_path=public as $$
declare old_cost numeric; margin numeric; sec uuid; ch public.flip_chains%rowtype; existing_pct numeric; item_type uuid; sell_secs numeric;
begin
 old_cost:=new.amount-new.fee-coalesce(new.seller_profit,0); margin:=case when old_cost>0 then round(100*coalesce(new.seller_profit,0)/old_cost,2) else 0 end; select item_type_id into item_type from public.inventory_items where id=new.item_id;
 insert into public.goal_events(profile_id,event_type,value,meta,created_at) values(new.buyer_id,'purchase',1,jsonb_build_object('amount',new.amount),new.completed_at),(new.seller_id,'sale',1,jsonb_build_object('profit',new.seller_profit,'margin_pct',margin),new.completed_at);
 select extract(epoch from(new.completed_at-l.created_at)) into sell_secs from public.listings l where l.id=new.listing_id; if sell_secs is not null and sell_secs<=1800 then insert into public.goal_events(profile_id,event_type,value,meta,created_at) values(new.seller_id,'fast_sale',1,jsonb_build_object('seconds',sell_secs),new.completed_at); end if;
 if exists(select 1 from public.offers where listing_id=new.listing_id and status='accepted') then insert into public.goal_events(profile_id,event_type,value,meta,created_at) values(new.buyer_id,'negotiated_trade',1,'{}',new.completed_at),(new.seller_id,'negotiated_trade',1,'{}',new.completed_at); end if;
 select id into sec from public.seasons where is_active and new.completed_at>=starts_at and new.completed_at<ends_at order by starts_at desc limit 1; if sec is not null then insert into public.profile_season_stats(season_id,profile_id,volume,purchases,unique_item_types) values(sec,new.buyer_id,new.amount,1,array[item_type]) on conflict(season_id,profile_id) do update set volume=profile_season_stats.volume+excluded.volume,purchases=profile_season_stats.purchases+1,unique_item_types=(select array_agg(distinct x) from unnest(profile_season_stats.unique_item_types||excluded.unique_item_types) x),updated_at=now(); insert into public.profile_season_stats(season_id,profile_id,volume,profit,sales,best_margin_pct,unique_item_types) values(sec,new.seller_id,new.amount,coalesce(new.seller_profit,0),1,greatest(margin,0),array[item_type]) on conflict(season_id,profile_id) do update set volume=profile_season_stats.volume+excluded.volume,profit=profile_season_stats.profit+excluded.profit,sales=profile_season_stats.sales+1,best_margin_pct=greatest(profile_season_stats.best_margin_pct,excluded.best_margin_pct),unique_item_types=(select array_agg(distinct x) from unnest(profile_season_stats.unique_item_types||excluded.unique_item_types) x),updated_at=now(); end if;
 select * into ch from public.flip_chains where profile_id=new.seller_id and is_active order by updated_at desc limit 1 for update; if not found or ch.current_capital<old_cost then if found then update public.flip_chains set is_active=false where id=ch.id; end if; insert into public.flip_chains(profile_id,start_capital,current_capital,trade_count,total_profit) values(new.seller_id,old_cost,new.amount,1,coalesce(new.seller_profit,0)) returning * into ch; else update public.flip_chains set current_capital=new.amount,trade_count=trade_count+1,total_profit=total_profit+coalesce(new.seller_profit,0),updated_at=now() where id=ch.id returning * into ch; end if; insert into public.flip_chain_steps(chain_id,trade_id,buy_price,sell_price,profit,created_at) values(ch.id,new.id,old_cost,new.amount,coalesce(new.seller_profit,0),new.completed_at) on conflict(trade_id) do nothing;
 select profit_pct into existing_pct from public.market_highlights where highlight_date=new.completed_at::date; if coalesce(new.seller_profit,0)>0 and (existing_pct is null or margin>existing_pct) then insert into public.market_highlights(highlight_date,trade_id,profile_id,item_id,profit,profit_pct,updated_at) values(new.completed_at::date,new.id,new.seller_id,new.item_id,new.seller_profit,margin,now()) on conflict(highlight_date) do update set trade_id=excluded.trade_id,profile_id=excluded.profile_id,item_id=excluded.item_id,profit=excluded.profit,profit_pct=excluded.profit_pct,updated_at=now() where excluded.profit_pct>market_highlights.profit_pct; if margin>=10 and (existing_pct is null or margin>=existing_pct+5) then insert into public.tradeup_announcements(body,is_active) values('Новый рекорд дня: сделка с маржой +'||trim(to_char(margin,'FM999990.0'))||'%. Рынок TradeUP написал эту историю сам.',true); end if; end if;
 return new;
end $$;
drop trigger if exists trades_progression on public.trades; create trigger trades_progression after insert on public.trades for each row execute function public.after_trade_progression();

create or replace function public.claim_daily_goal_atomic(p_profile_id uuid,p_goal_key text) returns integer language plpgsql security definer set search_path=public as $$ declare complete boolean:=false; reward integer:=0; begin
 if p_goal_key='first_sale' then select exists(select 1 from public.goal_events where profile_id=p_profile_id and event_type='sale' and created_at::date=current_date) into complete; reward:=80;
 elsif p_goal_key='margin_8' then select exists(select 1 from public.goal_events where profile_id=p_profile_id and event_type='sale' and created_at::date=current_date and coalesce((meta->>'margin_pct')::numeric,0)>=8) into complete; reward:=120;
 elsif p_goal_key='fast_sale' then select exists(select 1 from public.goal_events where profile_id=p_profile_id and event_type='fast_sale' and created_at::date=current_date) into complete; reward:=100;
 elsif p_goal_key='negotiate' then select exists(select 1 from public.goal_events where profile_id=p_profile_id and event_type='negotiated_trade' and created_at::date=current_date) into complete; reward:=90; else raise exception 'goal_not_found'; end if;
 if not complete then raise exception 'goal_not_complete'; end if; insert into public.goal_claims(profile_id,goal_key,goal_date,xp_awarded) values(p_profile_id,p_goal_key,current_date,reward) on conflict do nothing; if not found then raise exception 'goal_already_claimed'; end if; insert into public.profile_progress(profile_id,xp,level,updated_at) values(p_profile_id,reward,1+floor(reward/500.0)::int,now()) on conflict(profile_id) do update set xp=profile_progress.xp+reward,level=1+floor((profile_progress.xp+reward)/500.0)::int,updated_at=now(); return reward; end $$;

revoke all on function public.create_auction_atomic(uuid,uuid,text,numeric,integer) from public,anon,authenticated; grant execute on function public.create_auction_atomic(uuid,uuid,text,numeric,integer) to service_role;
revoke all on function public.place_auction_bid_atomic(uuid,uuid,numeric) from public,anon,authenticated; grant execute on function public.place_auction_bid_atomic(uuid,uuid,numeric) to service_role;
revoke all on function public.settle_auction_atomic(uuid) from public,anon,authenticated; grant execute on function public.settle_auction_atomic(uuid) to service_role;
revoke all on function public.settle_due_auctions(integer) from public,anon,authenticated; grant execute on function public.settle_due_auctions(integer) to service_role;
revoke all on function public.create_bundle_atomic(uuid,uuid[],text,text,numeric) from public,anon,authenticated; grant execute on function public.create_bundle_atomic(uuid,uuid[],text,text,numeric) to service_role;
revoke all on function public.cancel_bundle_atomic(uuid,uuid) from public,anon,authenticated; grant execute on function public.cancel_bundle_atomic(uuid,uuid) to service_role;
revoke all on function public.buy_bundle_atomic(uuid,uuid) from public,anon,authenticated; grant execute on function public.buy_bundle_atomic(uuid,uuid) to service_role;
revoke all on function public.claim_daily_goal_atomic(uuid,text) from public,anon,authenticated; grant execute on function public.claim_daily_goal_atomic(uuid,text) to service_role;
revoke all on function public.after_trade_progression() from public,anon,authenticated;
