insert into public.cosmetics_catalog (id,kind,name,description,stars_price,rarity,style_key,sort_order,is_active) values
('frame_amber_edge','frame','Amber Edge','Янтарный контур с мягким живым пульсом по краю.',45,'common','frame-amber-edge',10,true),
('frame_frost','frame','Frost','Холодный серебристый контур с медленным ледяным переливом.',65,'rare','frame-frost',20,true),
('frame_carbon','frame','Carbon','Графитовая фактура с тихим движением карбоновой сетки.',80,'rare','frame-carbon',30,true),
('frame_aurora','frame','Aurora','Анимированный холодный градиент, который плавно обходит аватар.',120,'epic','frame-aurora',40,true),
('frame_black_label','frame','Black Label','Премиальный чёрно-золотой контур с мягким золотым импульсом.',160,'legendary','frame-black-label',50,true),
('frame_ember','frame','Ember','Тёмная рамка с медленно бегущим медным жаром.',85,'rare','frame-ember',60,true),
('frame_titan','frame','Titan','Титановый контур с холодным металлическим бликом.',95,'rare','frame-titan',70,true),
('frame_orbit','frame','Orbit','Тёмная рамка с вращающимся световым акцентом.',110,'rare','frame-orbit',80,true),
('frame_copper_pulse','frame','Copper Pulse','Матовая медь с ритмичным пульсом по внешнему краю.',90,'rare','frame-copper-pulse',90,true),
('frame_liquid_silver','frame','Liquid Silver','Жидкий серебристый градиент с плавным движением по рамке.',130,'epic','frame-liquid-silver',100,true),
('frame_polar_shift','frame','Polar Shift','Полярный переход от стали к холодному синему с медленным сдвигом.',140,'epic','frame-polar-shift',110,true),
('frame_comet','frame','Comet','Тонкий световой след периодически проходит по периметру.',145,'epic','frame-comet',120,true),
('frame_royal_circuit','frame','Royal Circuit','Тёмное золото и точные движущиеся технологичные насечки.',165,'epic','frame-royal-circuit',130,true),
('frame_eclipse','frame','Eclipse','Почти чёрный контур с редким холодным затмением по краю.',180,'legendary','frame-eclipse',140,true),
('frame_vanta_rings','frame','Vanta Rings','Двойное тёмное кольцо с медленным встречным движением бликов.',210,'legendary','frame-vanta-rings',150,true),

('name_signal','name_style','Signal','Янтарное имя с едва заметным живым свечением.',35,'common','name-signal',210,true),
('name_chrome','name_style','Chrome','Металлический блик медленно проходит по буквам.',55,'rare','name-chrome',220,true),
('name_prism','name_style','Prism','Холодный многоцветный градиент постоянно смещается по имени.',95,'epic','name-prism',230,true),
('name_amber_flow','name_style','Amber Flow','Тёмное золото плавно течёт по тексту.',60,'rare','name-amber-flow',240,true),
('name_steel_sweep','name_style','Steel Sweep','Стальной световой проход без яркого неона.',75,'rare','name-steel-sweep',250,true),
('name_royal_fade','name_style','Royal Fade','Глубокий золотисто-фиолетовый перелив с медленной анимацией.',110,'epic','name-royal-fade',260,true),
('name_ghostline','name_style','Ghostline','Светлый холодный текст с редким призрачным бликом.',135,'legendary','name-ghostline',270,true),

('title_dealer','title','Перекуп','Компактный титул с мягким янтарным импульсом.',25,'common','title-dealer',410,true),
('title_collector','title','Коллекционер','Холодный титул с медленным движением тонкой каймы.',35,'common','title-collector',420,true),
('title_negotiator','title','Переговорщик','Фиолетово-стальной титул с плавным переливом.',45,'rare','title-negotiator',430,true),
('title_early','title','Early Dealer','Редкий ранний титул с живым золотым контуром.',70,'epic','title-early',440,true),
('title_arbitrageur','title','Арбитражник','Титул для тех, кто ищет разницу цен между сегментами рынка.',50,'rare','title-arbitrageur',450,true),
('title_market_maker','title','Маркет-мейкер','Анимированный титул для активных участников рынка.',75,'epic','title-market-maker',460,true),
('title_margin_hunter','title','Охотник за маржой','Премиальный титул с движущимся тёплым акцентом.',90,'epic','title-margin-hunter',470,true),
('title_tycoon','title','Магнат','Легендарный тёмно-золотой титул с редким мощным импульсом.',140,'legendary','title-tycoon',480,true),

('theme_obsidian','profile_theme','Obsidian','Глубокая чёрная тема с медленно дрейфующим мягким светом.',75,'rare','theme-obsidian',610,true),
('theme_graphite','profile_theme','Graphite','Графитовая сетка едва заметно движется по фону профиля.',90,'rare','theme-graphite',620,true),
('theme_amber_studio','profile_theme','Amber Studio','Тёмная студийная тема с плавным янтарным светом.',120,'epic','theme-amber-studio',630,true),
('theme_midnight_glass','profile_theme','Midnight Glass','Ночная стеклянная тема с медленным холодным бликом.',150,'legendary','theme-midnight-glass',640,true),
('theme_copper_room','profile_theme','Copper Room','Тёмная медная комната с мягким движением света.',95,'rare','theme-copper-room',650,true),
('theme_deep_ocean','profile_theme','Deep Ocean','Глубокий холодный фон с очень медленной волной света.',110,'epic','theme-deep-ocean',660,true),
('theme_titanium','profile_theme','Titanium','Стальной фон с направленным движущимся бликом.',130,'epic','theme-titanium',670,true),
('theme_eclipse','profile_theme','Eclipse','Легендарная почти чёрная тема с периодическим затмением по краю.',180,'legendary','theme-eclipse',680,true)
on conflict (id) do update set
  kind=excluded.kind,
  name=excluded.name,
  description=excluded.description,
  stars_price=excluded.stars_price,
  rarity=excluded.rarity,
  style_key=excluded.style_key,
  sort_order=excluded.sort_order,
  is_active=excluded.is_active,
  updated_at=now();